/*Please, run the ** npm install nodemailer ** command to install Nodemailer before run ** npm start **
here are the test data for the form submission
method : POST
URL : http://localhost:3030/form-submit
{
  "email": "test@example.com",  // Replace with any email you'd like to test
  "position": "sales",
  "fname": "John"
}
*/


const express = require('express');
var nodemailer = require('nodemailer');
const path = require('path');
const port = 3030

const app = express();
const router = express.Router();

router.use(express.json());
router.use(express.urlencoded({ extended: true}))

app.use('/', router)

router.get('/', (req, res) => {
  res.sendFile(path.join(`${__dirname}/Form.html`))
});

var transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: 'ploy.j0912@gmail.com', // its my email
      pass: 'qntw hnka ltdb zkqe' // The App Password from Google will expire on 17/02/2025.
    }
  });
  

router.post("/form-submit", function(req, res){
    const email = req.body.email;
    const position = req.body.position;
    const name = req.body.fname;

    //dd-mm-yyyy
    const deadline = new Date(new Date().setDate(new Date().getDate() + 7)).toLocaleDateString('en-GB').replace(/\//g, '-');
    
    console.log(`sending email to: ${email}, Position: ${position}, Name: ${name}`);
    // The following tasks are generated by ChatGPT
    
    const tasks = {
      sales: `\n\tTask Details: Your task is to develop a marketing strategy for our new product, "The Everlasting Quill." `,
      hr: `\n\tTask Details: You’ll be tasked with drafting a job description and interview questions for the Defense Against the Dark Arts Professor position, along with creating a scenario-based assessment to evaluate potential candidates. `,
      admin: `\n\tTask Details: For this skill test, you’ll be organizing the logistics for the upcoming Triwizard Tournament. You’ll be asked to prepare a schedule, identify potential challenges, and draft a memo to students about the event.`,
      programmer: `\n\tTask Details: You will develop a spell-checking charm for our enchanted library system. This task will help us ensure that our magical books are error-free and can be properly accessed by students and staff.`
    }


    var mailOptions = {
        from: 'ploy.j0912@gmail.com',
        to: email,
        subject: "Hogwarts Internship Skill Test",
        text: `Dear ${name}, \n\tWe are pleased to inform you that as part of the selection process for the ${position} position, you are invited to complete a skill test. This task will help us assess your abilities and provide you with a hands-on experience in a magical working environment.
\n\t${tasks[position]}
\n\tSubmission Deadline: ${deadline}
\n\tThe detailed instructions are attached for your reference. If you have any questions or require further clarification, feel free to reach out.
\nWe look forward to reviewing your work and wish you the best of luck!
\nBest regards,
Hogwarts School of Witchcraft and Wizardry
Human Resources Department`,
        attachments: [{
          filename: `${position}.jpg`,
          path: `${__dirname}/instructions/${position}.jpg`
        }] 
      };
      
      transporter.sendMail(mailOptions, function(error, info){
        if (error) {
          console.log(error);

        } else {
          console.log('Email sent: ' + info.response);
          res.status(200).send('Email has been sent successfully!');
        }
      });
    console.log(`Form submitted by ${email} at ${Date.now()} `);
})


app.listen(port, () => {
    console.log(`Server listening on port: 3030`)
})